### PR TITLE
fix typo in Subscription#pause

### PR DESCRIPTION
**Pull request by oktaras**
Hi, when I try to pause a subscription, I get an error from the server that the field 'remaining_pause_cycles' is required. After these changes, the pause is working.

### CODE REVIEW

**Comment by bhelx** [comment]
Thanks @oktaras . That code did seem to be incorrect. I'll get this reviewed and publish a bug fix.

File: Library/Subscription.cs [hunk 1]
```diff
@@ -692,6 +693,11 @@ internal override void ReadXml(XmlTextReader reader)
                             RemainingBillingCycles = billingCycles;
                         break;
 
+                    case "remaining_pause_cycles":
+                        if (Int32.TryParse(reader.ReadElementContentAsString(), out int pauseCycles))
```
Comment (bhelx) [inline Library/Subscription.cs]: There appears to be an issue here when travis is running the test:
```
Subscription.cs(697,85): error CS1644: Feature `declaration expression' cannot be used because it is not part of the C# 6.0 language specification
```

Comment (bhelx) [reply Library/Subscription.cs]: I think it's because `pauseCycles` needs to be declared.

Comment (oktaras) [reply Library/Subscription.cs]: @bhelx i can change, but this code works in c# 7.0 and higher https://blogs.msdn.microsoft.com/dotnet/2016/08/24/whats-new-in-csharp-7-0/

Comment (bhelx) [reply Library/Subscription.cs]: I understand, but we need it to continue to work in older versions.

Comment (oktaras) [reply Library/Subscription.cs]: Ok, I will change.

**Comment by bhelx** [comment]
Thanks so much for taking the time to fix this @oktaras. I'll get the bug fix out today.

**Comment by oktaras** [comment]
Thanks for quick problem resolve.

**Comment by bhelx** [comment]
This was released as `1.11.2`. It should show up in nuget soon: https://github.com/recurly/recurly-client-net/releases/tag/1.11.2
